const path = require('path')
const express = require('express')
const socketio = require('socket.io')
const app = new express
const http = require('http').createServer(app)
const io = socketio(http)
const { authenticateToken } = require('./controllers/jwt')
const { apLogin, apSign, apChange, apProfile } = require('./controllers/controller')
const { mainioController } = require('./controllers/servercontroller')
mainioController(io)
app.use(express.json())
app.use('/chatroom/', express.static(path.join(__dirname, 'public')))
app.post('/login', apLogin)
app.post('/sign', apSign)
app.post('/changepass', apChange)
app.get('/', authenticateToken, apProfile)
http.listen(8080, () => console.log("server is listennig on 8080 port"))
